### THIS FILE FOCUSES ON CREATING NATIONAL DATASET BY MERGING ALL CSVs TOGETHER

### What is OS?
os helps you work with your computer's file system.
- What folder am I currently in? os.getcwd()
- What's inside a folder? os.listdir("folder")
- Can I make a new folder? os.makedirs("newfolder", exist_ok=True)

In [9]:
import os
import pandas as pd

folder = "../State Datasets" 
# we're currently in scrapers
# go up one folder
# go to state datasets

In [14]:
os.listdir(folder)
# folder has all csv files + more!

['tamil_nadu.csv',
 'nagaland.csv',
 'himachal_pradesh.csv',
 'punjab.csv',
 'uttarakhand.csv',
 'delhi.csv',
 '.DS_Store',
 'manipur.csv',
 'jharkhand.csv',
 'assam.csv',
 'rajasthan.csv',
 'jammu_and_kashmir.csv',
 'tripura.csv',
 'karnataka.csv',
 'mizoram.csv',
 'puducherry.csv',
 'sikkim.csv',
 'arunachal_pradesh.csv',
 'madhya_pradesh.csv',
 'chhattisgarh.csv',
 'uttar_pradesh.csv',
 'odisha.csv',
 'chandigarh.csv',
 'goa.csv',
 'dadra_and_nagar_haveli_and_daman_and_diu.csv',
 'meghalaya.csv',
 'gujarat.csv',
 'lakshadweep.csv',
 'andhra_pradesh.csv',
 'andaman_and_nicobar_islands.csv',
 'kerala.csv',
 'telangana.csv',
 'haryana.csv',
 'ladakh.csv',
 'maharashtra.csv',
 'bihar.csv',
 'west_bengal.csv']

In [5]:
# getting all csv filenames in a list through list comprehension

csv_files = [
    file for file in os.listdir(folder) #os.listdir(folder) means show me everything inside this folder
    if file.endswith(".csv") #there will be all kinds of files like DS_Store etc. Keep only csv files.
]

csv_files

['tamil_nadu.csv',
 'nagaland.csv',
 'himachal_pradesh.csv',
 'punjab.csv',
 'uttarakhand.csv',
 'delhi.csv',
 'manipur.csv',
 'jharkhand.csv',
 'assam.csv',
 'rajasthan.csv',
 'jammu_and_kashmir.csv',
 'tripura.csv',
 'karnataka.csv',
 'mizoram.csv',
 'puducherry.csv',
 'sikkim.csv',
 'arunachal_pradesh.csv',
 'madhya_pradesh.csv',
 'chhattisgarh.csv',
 'uttar_pradesh.csv',
 'odisha.csv',
 'chandigarh.csv',
 'goa.csv',
 'dadra_and_nagar_haveli_and_daman_and_diu.csv',
 'meghalaya.csv',
 'gujarat.csv',
 'lakshadweep.csv',
 'andhra_pradesh.csv',
 'andaman_and_nicobar_islands.csv',
 'kerala.csv',
 'telangana.csv',
 'haryana.csv',
 'ladakh.csv',
 'maharashtra.csv',
 'bihar.csv',
 'west_bengal.csv']

In [23]:
# read every csv

from pandas.errors import EmptyDataError

all_dfs = []

for file in csv_files:
    filepath = os.path.join(folder, file)

    try: #I'm going to attempt something.
        df = pd.read_csv(filepath) #if it works, then it skips the except block entirely and goes to all_dfs.append(df)
    except EmptyDataError:
        print(f"Skipping empty file: {file}")
        continue

    all_dfs.append(df)

Skipping empty file: manipur.csv
Skipping empty file: mizoram.csv
Skipping empty file: goa.csv
Skipping empty file: andaman_and_nicobar_islands.csv
Skipping empty file: ladakh.csv

In [24]:
national = pd.concat(all_dfs, ignore_index=True)
national.to_csv("../national.csv", index=False)

In [25]:
len(national)

1122

In [26]:
national.head()

,sr_no,date_of_complaint,complaint_number,complainant_name_org,category_of_complaint,complaint,place_of_incident,violation_of_law,action_initiated,status,date_of_action_taken,state_id,page
0,1,12/04/2026,9-4/2026-27/3027/PCA,Unknown,-,"On 28.03.2026, a community puppy has been beat...","Kakkan St, Rathinapuri, Tatabad, Coimbatore - ...",-,-,-,21/04/2026,30,1
1,2,17/03/2026,9-4/2025-26/2917/PCA,Doctor Venkatesh,-,"Dr. Venkatesh of Lyka Pet Clinic, Dindigul, ha...",Appanaickenpalayam\r\nCoimbatore,-,-,-,21/04/2026,30,1
2,3,12/03/2026,9-4/2025-26/2900/PCA,security guards,-,I am writing to formally bring to your attenti...,Saveetha Engineering College\r\nSaveetha Nagar...,-,-,-,21/04/2026,30,1
3,4,04/02/2026,9-4/2025-26/2801/PCA,AOne Beef Stall,-,"Respected Sir / Madam,\r\n\r\nThis is bring to...","A-1 Beef Stall, M.S.Nagar, Near Sri Sai Super ...",-,-,-,13/02/2026,30,1
4,5,11/01/2026,9-4/2025-26/2732/PCA,-,-,"Dear Sir / Madam,\r\n\r\nI am Shivram from Che...","A-1 Beef Stall,\r\nM.S.Nagar,\r\nNear Sri Sai ...",-,-,-,15/01/2026,30,1

In [1]:
national["state_id"].value_counts(ascending=False)
#State-wise scraped complaint records total 1,122. This matches the sum of state-wise counts used for scraping. 
# The website’s overall count shows 1,156, leaving a discrepancy of 34 records, likely due to missing state values in those 34 records.

NameError: name 'national' is not defined

In [34]:
national["state_id"].value_counts().sum()
# so total complaints are actually 1122

np.int64(1122)

In [35]:
national.tail()

,sr_no,date_of_complaint,complaint_number,complainant_name_org,category_of_complaint,complaint,place_of_incident,violation_of_law,action_initiated,status,date_of_action_taken,state_id,page
1117,68,19/11/2023,9-13/2023-24/267/PCA,ASIT SAHA,-,A couple of cats and a couple of dogs regularl...,"VILL. P.O GOPALPUR, DIST. NORTH 24 PARGANAS, P...",-,-,-,03/01/2024,36,1
1118,69,12/11/2023,9-13/2023-24/258/PCA,Sekh Biki,-,I would like to complaint against the neighbor...,"Mithpukur Bhanga Masjid, Burdwan, Purba Bardhm...",-,-,-,03/01/2024,36,1
1119,70,12/11/2023,9-13/2023-24/257/PCA,Atanu Mallik,-,"Kicking, Beaten with sticks, Throwing stones t...","Daharpur (Near Daharpur High School), Tamluk, ...",-,-,-,08/11/2024,36,1
1120,71,29/10/2023,9-13/2023-24/243/PCA,-,-,A small white car dragged a helpless dog by ty...,"AG Block, Salt Lake, Kolkata-700091",-,-,-,03/01/2024,36,1
1121,72,07/08/2023,9-13/2023-24/155/PCA,Pushpendu Samanta,-,"I helplessly noticed that persons,named Pushpe...","27 Sisir Bagan Road, Behala, P.S.-Behala, Kolk...",-,-,-,10/07/2024,36,1

In [41]:
national.columns

Index(['sr_no', 'date_of_complaint', 'complaint_number',
       'complainant_name_org', 'category_of_complaint', 'complaint',
       'place_of_incident', 'violation_of_law', 'action_initiated', 'status',
       'date_of_action_taken', 'state_id', 'page'],
      dtype='str')